### ISSUE TITLE
Webpage not yet created for the repository

### ISSUE THREAD

**Issue by sanbabyfrancis** [fossvjcet/placement-prep#1]
Create webpage(s) similar to Collaborative Study Notes that indexes the contents of this repository. Create an index page (index.html) for each of the subdirectories as well. See https://github.com/fossvjcet/CS-S3

**Comment by krishnadevpmelevila** [comment]
Started working on it

**Comment by krishnadevpmelevila** [comment]
#2 issue resolved!
